server:
  port: 7777
spring:
  datasource:
      url: jdbc:mysql://localhost:3306/sg_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
      multipart:
          max-file-size: 2MB
          max-request-size: 5MB
  redis:
    port: 6379
    host: 192.168.1.7
    password: Aa1181552548
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    timeout: 5000ms
mybatis-plus:
    configuration:
      # 日志
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    global-config:
      db-config:
        logic-delete-field: delFlag
        logic-delete-value: 1
        logic-not-delete-value: 0
        id-type: auto


oss:
 accessKey: 4tAGlx9iPC5mgiVBQXukqWz0Qj6jmaM66lSi8AjW
 secretKey: fR5L7nY2sHn3ld2sZKeK4dJ0SPkQ1m4zao7Woj8v
 bucket: mmmblog
 exChainDn: rbwnyzmnc.hb-bkt.clouddn.com